{
  "formatVersion": "1.1",
  "component": {
    "group": "world.iskra",
    "module": "iskra-auth-client",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.42.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.42.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty",
          "version": {
            "requires": "1.44.1"
          }
        }
      ],
      "files": [
        {
          "name": "iskra-auth-client-0.4.2-plain.jar",
          "url": "iskra-auth-client-0.4.2-plain.jar",
          "size": 197639,
          "sha512": "180cea1227bb2ce51b5c92c6a305eb9ce8a5ec06e668502dbff9f6626d041996cc257a1367f6e17db211681ef97924e383912d40403e5262ced9e25f8f859ec1",
          "sha256": "af7dee686715405961d4f9b6641f58228e6765655b565c9973631cf35e0d8531",
          "sha1": "deed5a27f7d8d98a7fbbaaa500d8cd1744a6f1ca",
          "md5": "b1eb81a2bfb01da594aa56ddf1982b38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.github.kingbbode",
          "module": "spring-boot-custom-yaml-importer",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.6"
          }
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8"
        },
        {
          "group": "com.ninja-squad",
          "module": "springmockk",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "world.iskra",
          "module": "iskra-base-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "world.iskra",
          "module": "iskra-base-domain",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.42.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.42.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty",
          "version": {
            "requires": "1.44.1"
          }
        }
      ],
      "files": [
        {
          "name": "iskra-auth-client-0.4.2-plain.jar",
          "url": "iskra-auth-client-0.4.2-plain.jar",
          "size": 197639,
          "sha512": "180cea1227bb2ce51b5c92c6a305eb9ce8a5ec06e668502dbff9f6626d041996cc257a1367f6e17db211681ef97924e383912d40403e5262ced9e25f8f859ec1",
          "sha256": "af7dee686715405961d4f9b6641f58228e6765655b565c9973631cf35e0d8531",
          "sha1": "deed5a27f7d8d98a7fbbaaa500d8cd1744a6f1ca",
          "md5": "b1eb81a2bfb01da594aa56ddf1982b38"
        }
      ]
    }
  ]
}
