{
  "formatVersion": "1.1",
  "component": {
    "group": "world.iskra",
    "module": "iskra-auth-common",
    "version": "20221123180259",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "iskra-auth-common-20221123180259-plain.jar",
          "url": "iskra-auth-common-20221123180259-plain.jar",
          "size": 93100,
          "sha512": "bc6d88b70d830d4f6e4cf7c254ec3354423bbd972eddba041eafc3f4aeea6705daa15af691bfd59b00b77b1dc8b4e3b53724b5d14d7425dbbe785716d4b22a6f",
          "sha256": "6c49d0c4eeb3ec30a8f69a419218a3c4dfb3c7ced8461d0c1cef2fcbefdea5d2",
          "sha1": "839acc70a1f930774ac0225850837ed17a271b3b",
          "md5": "8b7376d13f3b917ffa78e8248668f7ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.github.kingbbode",
          "module": "spring-boot-custom-yaml-importer",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.6"
          }
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8"
        },
        {
          "group": "com.ninja-squad",
          "module": "springmockk",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "world.iskra",
          "module": "iskra-base-core",
          "version": {
            "requires": "20221123180259"
          }
        },
        {
          "group": "world.iskra",
          "module": "iskra-base-domain",
          "version": {
            "requires": "20221123180259"
          }
        },
        {
          "group": "world.iskra",
          "module": "iskra-auth-client",
          "version": {
            "requires": "20221123180259"
          }
        },
        {
          "group": "world.iskra",
          "module": "iskra-redis-common",
          "version": {
            "requires": "20221123180259"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis-reactive"
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-jackson",
          "version": {
            "requires": "0.11.2"
          }
        }
      ],
      "files": [
        {
          "name": "iskra-auth-common-20221123180259-plain.jar",
          "url": "iskra-auth-common-20221123180259-plain.jar",
          "size": 93100,
          "sha512": "bc6d88b70d830d4f6e4cf7c254ec3354423bbd972eddba041eafc3f4aeea6705daa15af691bfd59b00b77b1dc8b4e3b53724b5d14d7425dbbe785716d4b22a6f",
          "sha256": "6c49d0c4eeb3ec30a8f69a419218a3c4dfb3c7ced8461d0c1cef2fcbefdea5d2",
          "sha1": "839acc70a1f930774ac0225850837ed17a271b3b",
          "md5": "8b7376d13f3b917ffa78e8248668f7ee"
        }
      ]
    }
  ]
}
