{
  "formatVersion": "1.1",
  "component": {
    "group": "world.iskra",
    "module": "iskra-base-core",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "iskra-base-core-1.3.0-plain.jar",
          "url": "iskra-base-core-1.3.0-plain.jar",
          "size": 55510,
          "sha512": "3e7cef0d4e1d9cc5cbfedfc14694288f6b7d8388cfa3cc1a4e9542588e84398768e3f3949b09df5f959d8c45b19ecddb0ce8bccffd020b23c8f8edd959ae44c9",
          "sha256": "37a7a58794eb6bb290c32e56c700b8b129a5906b9310d1105ace59146cd6b5f2",
          "sha1": "148147cfaa92e181d933cb9f82e013631a5138e5",
          "md5": "9234a826066472be4a53af0d9d1fd335"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.github.kingbbode",
          "module": "spring-boot-custom-yaml-importer",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.6"
          }
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8"
        },
        {
          "group": "com.ninja-squad",
          "module": "springmockk",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "world.iskra",
          "module": "iskra-base-domain",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-jackson",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        }
      ],
      "files": [
        {
          "name": "iskra-base-core-1.3.0-plain.jar",
          "url": "iskra-base-core-1.3.0-plain.jar",
          "size": 55510,
          "sha512": "3e7cef0d4e1d9cc5cbfedfc14694288f6b7d8388cfa3cc1a4e9542588e84398768e3f3949b09df5f959d8c45b19ecddb0ce8bccffd020b23c8f8edd959ae44c9",
          "sha256": "37a7a58794eb6bb290c32e56c700b8b129a5906b9310d1105ace59146cd6b5f2",
          "sha1": "148147cfaa92e181d933cb9f82e013631a5138e5",
          "md5": "9234a826066472be4a53af0d9d1fd335"
        }
      ]
    }
  ]
}
