{
  "formatVersion": "1.1",
  "component": {
    "group": "world.iskra",
    "module": "iskra-base-core",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "iskra-base-core-1.3.1-plain.jar",
          "url": "iskra-base-core-1.3.1-plain.jar",
          "size": 56948,
          "sha512": "5c240307b5e2709889095d69a618924f6721a29123a1ce448a7f21a3f3d71690140ee09516bef758bbfe51442c98bc8c83195678a224b1b0db06706a10a8cffe",
          "sha256": "c5369f374ff9550e60ef6b0b05c649aefcc78bac087625516fc97f92b9b325ad",
          "sha1": "cc273724d9395331d59ed03a2a3f8ea444f5cb24",
          "md5": "f111a8ffec19f9a2ef2e0806e8dac914"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.github.kingbbode",
          "module": "spring-boot-custom-yaml-importer",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.6"
          }
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8"
        },
        {
          "group": "com.ninja-squad",
          "module": "springmockk",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "world.iskra",
          "module": "iskra-base-domain",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-jackson",
          "version": {
            "requires": "0.11.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "18.0"
          }
        }
      ],
      "files": [
        {
          "name": "iskra-base-core-1.3.1-plain.jar",
          "url": "iskra-base-core-1.3.1-plain.jar",
          "size": 56948,
          "sha512": "5c240307b5e2709889095d69a618924f6721a29123a1ce448a7f21a3f3d71690140ee09516bef758bbfe51442c98bc8c83195678a224b1b0db06706a10a8cffe",
          "sha256": "c5369f374ff9550e60ef6b0b05c649aefcc78bac087625516fc97f92b9b325ad",
          "sha1": "cc273724d9395331d59ed03a2a3f8ea444f5cb24",
          "md5": "f111a8ffec19f9a2ef2e0806e8dac914"
        }
      ]
    }
  ]
}
