{
  "formatVersion": "1.1",
  "component": {
    "group": "world.iskra",
    "module": "iskra-redis-common",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis-reactive"
        }
      ],
      "files": [
        {
          "name": "iskra-redis-common-1.0.1-plain.jar",
          "url": "iskra-redis-common-1.0.1-plain.jar",
          "size": 6764,
          "sha512": "bee3fce2ba536e90d98208caac44c042c95e97e34f3de7115b4f2bcf33277eb4392fd227c6386c2785dab60fb5f574f55c037a0b82636a54d46184968ee99a5f",
          "sha256": "1df8a35b29db718a6bd3cf9436254689cd9b8e13e5b72d8fa60e3477f38093e3",
          "sha1": "aa0a999eccd755375c3bcec956d6bc864ea14f7a",
          "md5": "b5294efcdbd3c21e6aededc2f1930dc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.github.kingbbode",
          "module": "spring-boot-custom-yaml-importer",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.6"
          }
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8"
        },
        {
          "group": "com.ninja-squad",
          "module": "springmockk",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-redis-reactive"
        }
      ],
      "files": [
        {
          "name": "iskra-redis-common-1.0.1-plain.jar",
          "url": "iskra-redis-common-1.0.1-plain.jar",
          "size": 6764,
          "sha512": "bee3fce2ba536e90d98208caac44c042c95e97e34f3de7115b4f2bcf33277eb4392fd227c6386c2785dab60fb5f574f55c037a0b82636a54d46184968ee99a5f",
          "sha256": "1df8a35b29db718a6bd3cf9436254689cd9b8e13e5b72d8fa60e3477f38093e3",
          "sha1": "aa0a999eccd755375c3bcec956d6bc864ea14f7a",
          "md5": "b5294efcdbd3c21e6aededc2f1930dc3"
        }
      ]
    }
  ]
}
