{
  "formatVersion": "1.1",
  "component": {
    "group": "world.iskra",
    "module": "iskra-base-domain",
    "version": "20221123180252",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "iskra-base-domain-20221123180252-plain.jar",
          "url": "iskra-base-domain-20221123180252-plain.jar",
          "size": 19563,
          "sha512": "2869081b27013446a0cbd3236c906247a7904b20c0c8eef54a33645277c7d570e6dfeb986679d917fb54e6cee2cfe7fda764a766546e8946d6549cb7360e25af",
          "sha256": "995cbd70049b6515de924a4dee3df28f02f8f45f54120b8afb156471d8aa0751",
          "sha1": "a7e3ae99ac18351b4789314f1f5add074dbebcda",
          "md5": "77317c4c058139b7c48b7f2b3e1fe986"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.github.kingbbode",
          "module": "spring-boot-custom-yaml-importer",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.6"
          }
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8"
        },
        {
          "group": "com.ninja-squad",
          "module": "springmockk",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "io.swagger",
          "module": "swagger-annotations",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "iskra-base-domain-20221123180252-plain.jar",
          "url": "iskra-base-domain-20221123180252-plain.jar",
          "size": 19563,
          "sha512": "2869081b27013446a0cbd3236c906247a7904b20c0c8eef54a33645277c7d570e6dfeb986679d917fb54e6cee2cfe7fda764a766546e8946d6549cb7360e25af",
          "sha256": "995cbd70049b6515de924a4dee3df28f02f8f45f54120b8afb156471d8aa0751",
          "sha1": "a7e3ae99ac18351b4789314f1f5add074dbebcda",
          "md5": "77317c4c058139b7c48b7f2b3e1fe986"
        }
      ]
    }
  ]
}
