{
  "formatVersion": "1.1",
  "component": {
    "group": "world.iskra",
    "module": "iskra-wallet-client",
    "version": "20221122142952",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.42.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.42.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty",
          "version": {
            "requires": "1.44.1"
          }
        }
      ],
      "files": [
        {
          "name": "iskra-wallet-client-20221122142952-plain.jar",
          "url": "iskra-wallet-client-20221122142952-plain.jar",
          "size": 285884,
          "sha512": "95355b56a2d5aac4f8d55ab0cdaa5db3ad35f08d05859a73ec410d8429c3f1cc331421b8e446fd7947a02a80a2a20ba809a6f924d04fb4c0b3daa8bdb58a9a37",
          "sha256": "317fe043b81063e99599878b684163f195dea8e733fd6d65e6825764eef0fdfc",
          "sha1": "8e120c6cd8bb6244b6e124f5150562ca661e0e7e",
          "md5": "7a401c48518327dc0d63bea27cc9d2ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.github.kingbbode",
          "module": "spring-boot-custom-yaml-importer",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.6"
          }
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8"
        },
        {
          "group": "com.ninja-squad",
          "module": "springmockk",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "world.iskra",
          "module": "iskra-base-core",
          "version": {
            "requires": "20221122142952"
          }
        },
        {
          "group": "world.iskra",
          "module": "iskra-base-domain",
          "version": {
            "requires": "20221122142952"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.42.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.42.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin",
          "version": {
            "requires": "3.19.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty",
          "version": {
            "requires": "1.44.1"
          }
        }
      ],
      "files": [
        {
          "name": "iskra-wallet-client-20221122142952-plain.jar",
          "url": "iskra-wallet-client-20221122142952-plain.jar",
          "size": 285884,
          "sha512": "95355b56a2d5aac4f8d55ab0cdaa5db3ad35f08d05859a73ec410d8429c3f1cc331421b8e446fd7947a02a80a2a20ba809a6f924d04fb4c0b3daa8bdb58a9a37",
          "sha256": "317fe043b81063e99599878b684163f195dea8e733fd6d65e6825764eef0fdfc",
          "sha1": "8e120c6cd8bb6244b6e124f5150562ca661e0e7e",
          "md5": "7a401c48518327dc0d63bea27cc9d2ca"
        }
      ]
    }
  ]
}
